application: gae-phonebook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: phonebook.application

- url: /profile/.*
  script: phonebook.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest